//Kobe Smith on 3/31/2026

/**
 * The RevenueReport class represents a report that summarizes the revenue generated by an airline.
 * It provides a method to print the report, which can include information such as total revenue,
 * revenue by flight, and revenue by ticket type.
 */
public class RevenueReport {
    /**
     * Prints the revenue report for the airline.
     */
    public void printReport(Airline airline, Revenue revenue) {
        System.out.println("Revenue Report for " + airline.getName());
        System.out.println("------------------------------");
        System.out.println("Economy Tickets Revenue: $" + revenue.getEconRevenue());
        System.out.println("Premium Tickets Revenue: $" + revenue.getPremRevenue());
        System.out.println("Business-Class Tickets Revenue: $" + revenue.getBusRevenue());
        System.out.println("First-Class Tickets Revenue: $" + revenue.getFirstRevenue());
        System.out.println("------------------------------");
        System.out.println("Total Revenue: $" + (revenue.getEconRevenue() + revenue.getPremRevenue() + revenue.getBusRevenue() + revenue.getFirstRevenue()));
    }
}