/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kobed
 */
public class AmsFrame extends javax.swing.JFrame {

    Application app = new Application();
    /**
     * Creates new form AmsFrame
     */
    public AmsFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbnUserType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        radPassenger = new javax.swing.JRadioButton();
        radStaff = new javax.swing.JRadioButton();
        radManager = new javax.swing.JRadioButton();
        radHumanResources = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to SkyHigh Airlines!");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbnUserType.add(radPassenger);
        radPassenger.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radPassenger.setText("Passenger");
        radPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPassengerActionPerformed(evt);
            }
        });

        rbnUserType.add(radStaff);
        radStaff.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radStaff.setText("Staff");
        radStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radStaffActionPerformed(evt);
            }
        });

        rbnUserType.add(radManager);
        radManager.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radManager.setText("Manager");
        radManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radManagerActionPerformed(evt);
            }
        });

        rbnUserType.add(radHumanResources);
        radHumanResources.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radHumanResources.setText("Human Resources");
        radHumanResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHumanResourcesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radStaff)
                            .addComponent(radPassenger)
                            .addComponent(radManager)
                            .addComponent(radHumanResources))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(radPassenger)
                .addGap(18, 18, 18)
                .addComponent(radStaff)
                .addGap(18, 18, 18)
                .addComponent(radManager)
                .addGap(18, 18, 18)
                .addComponent(radHumanResources)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPassengerActionPerformed
        passengerFrame passenger = new passengerFrame();
        passenger.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_radPassengerActionPerformed

    private void radStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radStaffActionPerformed
        staffFrame staff = new staffFrame();
        staff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_radStaffActionPerformed

    private void radManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radManagerActionPerformed
        // TODO add your handling code here:
        ManagerFrame manager = new ManagerFrame();
        manager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_radManagerActionPerformed

    private void radHumanResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHumanResourcesActionPerformed
        humanResourcesFrame hr = new humanResourcesFrame();
        hr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_radHumanResourcesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AmsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radHumanResources;
    private javax.swing.JRadioButton radManager;
    private javax.swing.JRadioButton radPassenger;
    private javax.swing.JRadioButton radStaff;
    private javax.swing.ButtonGroup rbnUserType;
    // End of variables declaration//GEN-END:variables
}
