
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kobed
 */
public class CockpitMenu extends javax.swing.JFrame {

    private final CockpitCrew cockpit;
    /**
     * Creates new form CockpitMenu
     */
    public CockpitMenu(CockpitCrew cockpit) {
        initComponents();
        setLocationRelativeTo(null);
        this.cockpit = cockpit;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabCockpitCrew = new javax.swing.JTabbedPane();
        tabCockpitFlightSchedule = new javax.swing.JPanel();
        lblSchedule = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        tabFly = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaCockpit = new javax.swing.JTextArea();
        lblAttendantFlights = new javax.swing.JLabel();
        btnFly = new javax.swing.JButton();
        txtFlightID = new javax.swing.JTextField();
        btnFlyBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblSchedule.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSchedule.setText("SkyHigh Flight Schedule:");

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Origin", "Destination", "Gate", "Departure", "Arrival"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblSchedule);

        javax.swing.GroupLayout tabCockpitFlightScheduleLayout = new javax.swing.GroupLayout(tabCockpitFlightSchedule);
        tabCockpitFlightSchedule.setLayout(tabCockpitFlightScheduleLayout);
        tabCockpitFlightScheduleLayout.setHorizontalGroup(
            tabCockpitFlightScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCockpitFlightScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCockpitFlightScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCockpitFlightScheduleLayout.createSequentialGroup()
                        .addComponent(lblSchedule)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabCockpitFlightScheduleLayout.setVerticalGroup(
            tabCockpitFlightScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCockpitFlightScheduleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabCockpitCrew.addTab("View Flight Schedule", tabCockpitFlightSchedule);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Enter Flight ID:");

        txtAreaCockpit.setEditable(false);
        txtAreaCockpit.setColumns(20);
        txtAreaCockpit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtAreaCockpit.setRows(5);
        jScrollPane3.setViewportView(txtAreaCockpit);

        lblAttendantFlights.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblAttendantFlights.setText("Your Assigned Flights:");

        btnFly.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnFly.setText("Fly Aircraft");
        btnFly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlyActionPerformed(evt);
            }
        });

        btnFlyBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnFlyBack.setText("Back");
        btnFlyBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlyBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabFlyLayout = new javax.swing.GroupLayout(tabFly);
        tabFly.setLayout(tabFlyLayout);
        tabFlyLayout.setHorizontalGroup(
            tabFlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFlyLayout.createSequentialGroup()
                .addGroup(tabFlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabFlyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabFlyLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblAttendantFlights))
                    .addGroup(tabFlyLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(tabFlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnFlyBack))
                        .addGap(18, 18, 18)
                        .addGroup(tabFlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFly)
                            .addComponent(txtFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        tabFlyLayout.setVerticalGroup(
            tabFlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabFlyLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblAttendantFlights)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabFlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabFlyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFly)
                    .addComponent(btnFlyBack))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tabCockpitCrew.addTab("Fly Aircraft", tabFly);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCockpitCrew)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabCockpitCrew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            BufferedReader br = new BufferedReader(new FileReader("flights.txt"));
            BufferedReader br1 = new BufferedReader(new FileReader("staffAssigned.txt"));

            String line;
    
            DefaultTableModel model = (DefaultTableModel) tblSchedule.getModel();
    
            while ((line = br.readLine()) != null) {
                String[] rowData = line.split(",");
                model.addRow(rowData);
            }
            
            txtAreaCockpit.setText("");

            while ((line = br1.readLine()) != null) {
                if (line.contains(cockpit.getName())) {
                    txtAreaCockpit.append(line + "\n");
                }
            }
            
            br.close();
            br1.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnFlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlyActionPerformed
        String flight = txtFlightID.getText();
        File input = new File("staffAssigned.txt");
        File output = new File("temp.txt");
        
        String lineToRemove = "Staff: " + cockpit.getName() + " - Department: " + cockpit.getDepartment() + " - Flight: " + flight;
        
        try {
            BufferedReader reader = new BufferedReader(new FileReader(input));
            BufferedWriter writer = new BufferedWriter(new FileWriter(output));

            String line;
    
            txtAreaCockpit.setText("");

            while ((line = reader.readLine()) != null) {
                if (line.equals(lineToRemove)) {
                    continue;
                }
                writer.write(line);
                writer.newLine();
            }
            reader.close();
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        input.delete();
        output.renameTo(input);
        JOptionPane.showMessageDialog(this, "Now Prepping flight " + flight + " for takeoff! Your schedule will be updated.");
    }//GEN-LAST:event_btnFlyActionPerformed

    private void btnFlyBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlyBackActionPerformed
        staffFrame staff = new staffFrame();
        staff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFlyBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CockpitMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CockpitMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CockpitMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CockpitMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CockpitCrew cockpit = new CockpitCrew();
                new CockpitMenu(cockpit).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFly;
    private javax.swing.JButton btnFlyBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAttendantFlights;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JTabbedPane tabCockpitCrew;
    private javax.swing.JPanel tabCockpitFlightSchedule;
    private javax.swing.JPanel tabFly;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextArea txtAreaCockpit;
    private javax.swing.JTextField txtFlightID;
    // End of variables declaration//GEN-END:variables
}
