
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.File;
import java.io.BufferedWriter;
import java.io.FileWriter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kobed
 */
public class passengerMenu extends javax.swing.JFrame {

    private final Passenger passenger;
    Application app = new Application();
    /**
     * Creates new form passengerMenu
     */
    public passengerMenu(Passenger passenger) {
        initComponents();
        setLocationRelativeTo(null);
        this.passenger = passenger;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabBook = new javax.swing.JPanel();
        lblFlights = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAvailableFlights = new javax.swing.JTable();
        btnBookBack = new javax.swing.JButton();
        tabCancelBooking = new javax.swing.JPanel();
        btnCancelBooking = new javax.swing.JButton();
        lblYourFlights = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblYourFlights = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnCancelBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblFlights.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblFlights.setText("Available Flights:");

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        tblAvailableFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Origin", "Destination", "Gate", "Departure", "Arrival"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblAvailableFlights);
        if (tblAvailableFlights.getColumnModel().getColumnCount() > 0) {
            tblAvailableFlights.getColumnModel().getColumn(0).setResizable(false);
            tblAvailableFlights.getColumnModel().getColumn(1).setResizable(false);
            tblAvailableFlights.getColumnModel().getColumn(2).setResizable(false);
            tblAvailableFlights.getColumnModel().getColumn(3).setResizable(false);
            tblAvailableFlights.getColumnModel().getColumn(5).setResizable(false);
        }

        btnBookBack.setText("Back");
        btnBookBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabBookLayout = new javax.swing.GroupLayout(tabBook);
        tabBook.setLayout(tabBookLayout);
        tabBookLayout.setHorizontalGroup(
            tabBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBookLayout.createSequentialGroup()
                .addGroup(tabBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(tabBookLayout.createSequentialGroup()
                        .addGroup(tabBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabBookLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(lblFlights))
                            .addGroup(tabBookLayout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(btnBookBack)
                                .addGap(86, 86, 86)
                                .addComponent(btnBook)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabBookLayout.setVerticalGroup(
            tabBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabBookLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblFlights)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBook)
                    .addComponent(btnBookBack))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Book Flight", tabBook);

        btnCancelBooking.setText("Cancel Booking");
        btnCancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBookingActionPerformed(evt);
            }
        });

        lblYourFlights.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblYourFlights.setText("Your Bookings");

        tblYourFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Flight ID", "Origin", "Destination", "Gate", "Departure", "Arrival"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblYourFlights);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancelBack.setText("Back");
        btnCancelBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCancelBookingLayout = new javax.swing.GroupLayout(tabCancelBooking);
        tabCancelBooking.setLayout(tabCancelBookingLayout);
        tabCancelBookingLayout.setHorizontalGroup(
            tabCancelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCancelBookingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelBack)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnCancelBooking)
                .addGap(130, 130, 130))
            .addGroup(tabCancelBookingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tabCancelBookingLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(lblYourFlights)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabCancelBookingLayout.setVerticalGroup(
            tabCancelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCancelBookingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblYourFlights)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabCancelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelBooking)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancelBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel Booking", tabCancelBooking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            BufferedReader br = new BufferedReader(new FileReader("flights.txt"));
            BufferedReader br1 = new BufferedReader(new FileReader("purchasedTickets.txt"));

            String line;
    
            DefaultTableModel model = (DefaultTableModel) tblAvailableFlights.getModel();
            DefaultTableModel model1 = (DefaultTableModel) tblYourFlights.getModel();
    
            while ((line = br.readLine()) != null) {
                String[] rowData = line.split(",");
                model.addRow(rowData);
            }
            
            while ((line = br1.readLine()) != null) {
                if (line.toLowerCase().contains(passenger.getName().toLowerCase())) {
                    String[] rowData = line.split(",");
                    model1.addRow(rowData);
                }
            }
            
            br.close();
            br1.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        Flight flight = new Flight();

        int row = tblAvailableFlights.getSelectedRow();
        flight.setFlightId(tblAvailableFlights.getValueAt(row, 0).toString());
        flight.setOrigin(tblAvailableFlights.getValueAt(row, 1).toString());
        flight.setDestination(tblAvailableFlights.getValueAt(row, 2).toString());
        flight.setGate(tblAvailableFlights.getValueAt(row, 3).toString());
        flight.setDepartureTime(tblAvailableFlights.getValueAt(row, 4).toString());
        flight.setArrivalTime(tblAvailableFlights.getValueAt(row, 5).toString());

        ticketTypes tickets = new ticketTypes(flight);
        tickets.setVisible(true);
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnCancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBookingActionPerformed
        int selected = tblYourFlights.getSelectedRow();
        File input = new File("purchasedTickets.txt");
        File output = new File("temp.txt");
        
        String name = tblYourFlights.getValueAt(selected, 0).toString();
        String flightID = tblYourFlights.getValueAt(selected, 1).toString();
        String origin = tblYourFlights.getValueAt(selected, 2).toString();
        String destination = tblYourFlights.getValueAt(selected, 3).toString();
        String gate = tblYourFlights.getValueAt(selected, 4).toString();
        String departure = tblYourFlights.getValueAt(selected, 5).toString();
        String arrival = tblYourFlights.getValueAt(selected, 6).toString();
        
        //String lineToRemove = name + ", " + flightID + ", " + origin + ", " + destination + ", " + gate + ", " + departure + ", " + arrival;
        
        if (selected != -1) {
            DefaultTableModel model = (DefaultTableModel) tblYourFlights.getModel();
            int choice = JOptionPane.showConfirmDialog(this, "Confirm Cancellation.",
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                model.removeRow(selected);
                JOptionPane.showMessageDialog(this, "You should expect your refund in 2-3 business days.");
                try {
                    BufferedReader reader = new BufferedReader(new FileReader(input));
                    BufferedWriter writer = new BufferedWriter(new FileWriter(output));

                    String line;
                    boolean removed = false;
                    
                    while ((line = reader.readLine()) != null) {
                        String[] parts = line.split(",");

                        if (parts.length >= 7) {
                            if (parts[0].trim().equalsIgnoreCase(name.trim()) &&
                                parts[1].trim().equalsIgnoreCase(flightID.trim()) &&
                                parts[2].trim().equalsIgnoreCase(origin.trim()) &&
                                parts[3].trim().equalsIgnoreCase(destination.trim()) &&
                                parts[4].trim().equalsIgnoreCase(gate.trim()) &&
                                parts[5].trim().equalsIgnoreCase(departure.trim()) &&
                                parts[6].trim().equalsIgnoreCase(arrival.trim())) {

                                System.out.println("MATCH FOUND → REMOVING");
                                continue;
                            }
                        }
                        writer.write(line);
                        writer.newLine();
                    }
                    reader.close();
                    writer.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                input.delete();
                output.renameTo(input);
            }
        } else {
            System.out.println("No row selected.");
        }
    }//GEN-LAST:event_btnCancelBookingActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            BufferedReader br1 = new BufferedReader(new FileReader("purchasedTickets.txt"));

            String line;
    
            DefaultTableModel model1 = (DefaultTableModel) tblYourFlights.getModel();
            model1.setRowCount(0);
            
            while ((line = br1.readLine()) != null) {
                if (line.toLowerCase().contains(passenger.getName().toLowerCase())) {
                    String[] rowData = line.split(",");
                    model1.addRow(rowData);
                }
            }
            
            br1.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBookBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookBackActionPerformed
        passengerFrame pass = new passengerFrame();
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookBackActionPerformed

    private void btnCancelBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelBackActionPerformed
        passengerFrame pass = new passengerFrame();
        pass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passengerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Passenger passenger = new Passenger();
                new passengerMenu(passenger).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnBookBack;
    private javax.swing.JButton btnCancelBack;
    private javax.swing.JButton btnCancelBooking;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblFlights;
    private javax.swing.JLabel lblYourFlights;
    private javax.swing.JPanel tabBook;
    private javax.swing.JPanel tabCancelBooking;
    private javax.swing.JTable tblAvailableFlights;
    private javax.swing.JTable tblYourFlights;
    // End of variables declaration//GEN-END:variables
}
