
import java.io.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kobed
 */
public class passengerFrame extends javax.swing.JFrame {

    Application app = new Application();
    /**
     * Creates new form passengerFrame
     */
    public passengerFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPassenger = new javax.swing.JTabbedPane();
        tabCreatePassAccount = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        txtNewEmail = new javax.swing.JTextField();
        txtNewPnr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCreateBack = new javax.swing.JButton();
        tabPassLogIn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPnr = new javax.swing.JTextField();
        btnLogIn = new javax.swing.JButton();
        btnLogBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabPassenger.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPassengerStateChanged(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Email:");

        jLabel3.setText("PNR:");

        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCreateBack.setText("Back");
        btnCreateBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCreatePassAccountLayout = new javax.swing.GroupLayout(tabCreatePassAccount);
        tabCreatePassAccount.setLayout(tabCreatePassAccountLayout);
        tabCreatePassAccountLayout.setHorizontalGroup(
            tabCreatePassAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCreatePassAccountLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(tabCreatePassAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCreatePassAccountLayout.createSequentialGroup()
                        .addGroup(tabCreatePassAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCreatePassAccountLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabCreatePassAccountLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabCreatePassAccountLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNewPnr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabCreatePassAccountLayout.createSequentialGroup()
                        .addComponent(btnCreateBack)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38))))
        );
        tabCreatePassAccountLayout.setVerticalGroup(
            tabCreatePassAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCreatePassAccountLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(tabCreatePassAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(tabCreatePassAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(tabCreatePassAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewPnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(tabCreatePassAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateBack)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        tabPassenger.addTab("Create Passenger Account", tabCreatePassAccount);

        jLabel4.setText("Name:");

        jLabel5.setText("PNR:");

        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnLogBack.setText("Back");
        btnLogBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabPassLogInLayout = new javax.swing.GroupLayout(tabPassLogIn);
        tabPassLogIn.setLayout(tabPassLogInLayout);
        tabPassLogInLayout.setHorizontalGroup(
            tabPassLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPassLogInLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(tabPassLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabPassLogInLayout.createSequentialGroup()
                        .addGroup(tabPassLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabPassLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPnr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabPassLogInLayout.createSequentialGroup()
                        .addComponent(btnLogBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogIn)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        tabPassLogInLayout.setVerticalGroup(
            tabPassLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPassLogInLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(tabPassLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabPassLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(tabPassLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(btnLogBack))
                .addGap(18, 18, 18))
        );

        tabPassenger.addTab("Log In", tabPassLogIn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPassenger)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPassenger)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = txtNewName.getText();
        String email = txtNewEmail.getText();
        String Pnr = txtNewPnr.getText();
        Passenger passenger = new Passenger(name, email, Pnr);
        try {
            FileWriter fw = new FileWriter("passengers.txt", true);
            fw.write("\n" + name + ", " + email + ", " + Pnr);
            fw.close();
            txtNewName.setText("");
            txtNewEmail.setText("");
            txtNewPnr.setText("");
        } catch (IOException e) {
            System.err.println("Error updating file: " + e.getMessage());
        }
        JOptionPane.showMessageDialog(this, "Account created successfully! A confirmation email has been sent to " + txtNewEmail.getText());
        passengerMenu passMenu = new passengerMenu(passenger);
        passMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        String passengerData = "passengers.txt";
        System.out.println(new File(passengerData).getAbsolutePath());
        boolean found = false;
        try (BufferedReader br = new BufferedReader(new FileReader(passengerData))) {
            String line;
            int lineNumber = 0;

            while ((line = br.readLine()) != null) {
                lineNumber++;
                String[] parts = line.split(",");
                String email = parts[1];
                // Case-insensitive search
                if (line.toLowerCase().contains(txtName.getText().toLowerCase()) && line.contains(txtPnr.getText())) {
                    Passenger passenger1 = new Passenger(txtName.getText(), email,txtPnr.getText());
                    System.out.println("Found on line " + lineNumber + ": " + line);
                    found = true;
                    JOptionPane.showMessageDialog(this, "Welcome Back " + txtName.getText() + "!");
                    passengerMenu passenger = new passengerMenu(passenger1);
                    passenger.setVisible(true);
                    this.dispose();
                }
            }

            if (!found) {
                System.out.println("Passenger not found in file.");
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void tabPassengerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPassengerStateChanged
        txtNewName.setText("");
        txtNewEmail.setText("");
        txtNewPnr.setText("");
        txtName.setText("");
        txtPnr.setText("");
    }//GEN-LAST:event_tabPassengerStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //To-DO
    }//GEN-LAST:event_formWindowClosed

    private void btnCreateBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBackActionPerformed
        AmsFrame ams = new AmsFrame();
        ams.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateBackActionPerformed

    private void btnLogBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogBackActionPerformed
        AmsFrame ams = new AmsFrame();
        ams.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passengerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passengerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passengerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passengerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passengerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBack;
    private javax.swing.JButton btnLogBack;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel tabCreatePassAccount;
    private javax.swing.JPanel tabPassLogIn;
    private javax.swing.JTabbedPane tabPassenger;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtNewPnr;
    private javax.swing.JTextField txtPnr;
    // End of variables declaration//GEN-END:variables
}
