
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kobed
 */
public class ticketTypes extends javax.swing.JFrame {

    private final Flight flight;
    /**
     * Creates new form ticketTypes
     * @param flight
     */
    public ticketTypes(Flight flight) {
        initComponents();
        setLocationRelativeTo(null);
        this.flight = flight;
        
        lblFlightID.setText(flight.getFlightID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentMethod = new javax.swing.ButtonGroup();
        pnlPaymentMethod = new javax.swing.JPanel();
        radCash = new javax.swing.JRadioButton();
        radCard = new javax.swing.JRadioButton();
        txtPrice = new javax.swing.JTextField();
        btnPurchase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlCard = new javax.swing.JPanel();
        lblCardNumber = new javax.swing.JLabel();
        lblExpiration = new javax.swing.JLabel();
        lblCvv = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        txtExpiration = new javax.swing.JTextField();
        txtCvv = new javax.swing.JTextField();
        pnlTicketTypes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicketTypes = new javax.swing.JTable();
        lblFlightID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPaymentName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlPaymentMethod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        paymentMethod.add(radCash);
        radCash.setText("Cash");
        radCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCashActionPerformed(evt);
            }
        });

        paymentMethod.add(radCard);
        radCard.setSelected(true);
        radCard.setText("Card");
        radCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPaymentMethodLayout = new javax.swing.GroupLayout(pnlPaymentMethod);
        pnlPaymentMethod.setLayout(pnlPaymentMethodLayout);
        pnlPaymentMethodLayout.setHorizontalGroup(
            pnlPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentMethodLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(radCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(radCard)
                .addGap(14, 14, 14))
        );
        pnlPaymentMethodLayout.setVerticalGroup(
            pnlPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentMethodLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlPaymentMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCard)
                    .addComponent(radCash))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtPrice.setEditable(false);

        btnPurchase.setText("Purchase Ticket");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Total:");

        pnlCard.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Card Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        lblCardNumber.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblCardNumber.setText("Card Number:");

        lblExpiration.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblExpiration.setText("Expiration Date (MM/YY):");

        lblCvv.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblCvv.setText("CVV:");

        javax.swing.GroupLayout pnlCardLayout = new javax.swing.GroupLayout(pnlCard);
        pnlCard.setLayout(pnlCardLayout);
        pnlCardLayout.setHorizontalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addComponent(lblExpiration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExpiration, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addComponent(lblCardNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addComponent(lblCvv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCardLayout.setVerticalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardNumber)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpiration)
                    .addComponent(txtExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCvv)
                    .addComponent(txtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        tblTicketTypes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Ticket ID", "PNR", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTicketTypes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTicketTypesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTicketTypes);

        lblFlightID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlTicketTypesLayout = new javax.swing.GroupLayout(pnlTicketTypes);
        pnlTicketTypes.setLayout(pnlTicketTypesLayout);
        pnlTicketTypesLayout.setHorizontalGroup(
            pnlTicketTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTicketTypesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTicketTypesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        pnlTicketTypesLayout.setVerticalGroup(
            pnlTicketTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTicketTypesLayout.createSequentialGroup()
                .addComponent(lblFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pnlTicketTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnPurchase))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(pnlPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaymentName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlTicketTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPaymentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addComponent(btnPurchase)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            BufferedReader br = new BufferedReader(new FileReader("tickets.txt"));
            String line;
    
            DefaultTableModel model = (DefaultTableModel) tblTicketTypes.getModel();
    
            while ((line = br.readLine()) != null) {
                String[] rowData = line.split(",");
                model.addRow(rowData);
            }
    
            br.close();
    
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void radCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCardActionPerformed
        if (radCard.isSelected()) {
            pnlCard.setVisible(true);
        }
    }//GEN-LAST:event_radCardActionPerformed

    private void radCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCashActionPerformed
        if (radCash.isSelected()) {
            pnlCard.setVisible(false);
        }
    }//GEN-LAST:event_radCashActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        if (radCash.isSelected()) {
            String name = txtPaymentName.getText();
            String price = txtPrice.getText();
            try {
                FileWriter fw = new FileWriter("payments.txt", true);
                FileWriter fw1 = new FileWriter("purchasedTickets.txt", true);
                fw.write("\n" + name + "," + price);
                fw1.write("\n" + txtPaymentName.getText() + ", " + flight.getFlightID() + "," + flight.getOrigin() + "," + flight.getDestination() + 
                        "," + flight.getGate()+ "," + flight.getDepartureTime() + "," + flight.getArrivalTime());
                fw.close();
                fw1.close();
                txtPaymentName.setText("");
                txtPrice.setText("");
                JOptionPane.showMessageDialog(this, "Payment has been successfully processed. Thank you.");
                this.dispose();
            } catch (IOException e) {
                System.err.println("Error updating file: " + e.getMessage());
            }
        }
        else if (radCard.isSelected()) {
            String name = txtPaymentName.getText();
            String cardNum = txtCardNumber.getText();
            String exp = txtExpiration.getText();
            String cvv = txtCvv.getText();
            String price = txtPrice.getText();
            try {
                FileWriter fw = new FileWriter("payments.txt", true);
                FileWriter fw1 = new FileWriter("purchasedTickets.txt", true);
                fw.write("\n" + name + "," + cardNum + "," + exp + ", " + cvv + "," + price);
                fw1.write("\n" + txtPaymentName.getText() + ", " + flight.getFlightID() + "," + flight.getOrigin() + "," + flight.getDestination() + 
                        ",Gate" + flight.getGate()+ "," + flight.getDepartureTime() + "," + flight.getArrivalTime());
                fw.close();
                fw1.close();
                txtPaymentName.setText("");
                txtPrice.setText("");
                JOptionPane.showMessageDialog(this, "Payment has been successfully processed. Thank you.");
                this.dispose();
            } catch (IOException e) {
                System.err.println("Error updating file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void tblTicketTypesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTicketTypesMouseClicked
        int row = tblTicketTypes.getSelectedRow();
        txtPrice.setText(tblTicketTypes.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblTicketTypesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketTypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Flight flight = new Flight();
                new ticketTypes(flight).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblCvv;
    private javax.swing.JLabel lblExpiration;
    private javax.swing.JLabel lblFlightID;
    private javax.swing.ButtonGroup paymentMethod;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlPaymentMethod;
    private javax.swing.JPanel pnlTicketTypes;
    private javax.swing.JRadioButton radCard;
    private javax.swing.JRadioButton radCash;
    private javax.swing.JTable tblTicketTypes;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtExpiration;
    private javax.swing.JTextField txtPaymentName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
