
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kobed
 */
public class AttendantMenu extends javax.swing.JFrame {

    private final FlightAttendants attendant;
    /**
     * Creates new form AttendantMenu
     */
    public AttendantMenu(FlightAttendants attendant) {
        initComponents();
        setLocationRelativeTo(null);
        this.attendant = attendant;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabFlightAttendant = new javax.swing.JTabbedPane();
        tabAttendantFlightSchedule = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        tabSafetyDemo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaAttendant = new javax.swing.JTextArea();
        btnSafetyDemo = new javax.swing.JButton();
        lblPerformID = new javax.swing.JLabel();
        txtFlightID = new javax.swing.JTextField();
        btnPerformBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("SkyHigh Flight Schedule:");

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Origin", "Destination", "Gate", "Departure", "Arrival"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblSchedule);
        if (tblSchedule.getColumnModel().getColumnCount() > 0) {
            tblSchedule.getColumnModel().getColumn(1).setResizable(false);
            tblSchedule.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout tabAttendantFlightScheduleLayout = new javax.swing.GroupLayout(tabAttendantFlightSchedule);
        tabAttendantFlightSchedule.setLayout(tabAttendantFlightScheduleLayout);
        tabAttendantFlightScheduleLayout.setHorizontalGroup(
            tabAttendantFlightScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAttendantFlightScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAttendantFlightScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        tabAttendantFlightScheduleLayout.setVerticalGroup(
            tabAttendantFlightScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAttendantFlightScheduleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabFlightAttendant.addTab("View Flight Schedule", tabAttendantFlightSchedule);

        jLabel3.setText("Your Flights:");

        txtAreaAttendant.setEditable(false);
        txtAreaAttendant.setColumns(20);
        txtAreaAttendant.setRows(5);
        jScrollPane3.setViewportView(txtAreaAttendant);

        btnSafetyDemo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSafetyDemo.setText("Perform Demonstration");
        btnSafetyDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSafetyDemoActionPerformed(evt);
            }
        });

        lblPerformID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblPerformID.setText("Enter Flight ID:");

        btnPerformBack.setText("Back");
        btnPerformBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabSafetyDemoLayout = new javax.swing.GroupLayout(tabSafetyDemo);
        tabSafetyDemo.setLayout(tabSafetyDemoLayout);
        tabSafetyDemoLayout.setHorizontalGroup(
            tabSafetyDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSafetyDemoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabSafetyDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(tabSafetyDemoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPerformID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabSafetyDemoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPerformBack)
                .addGap(18, 18, 18)
                .addComponent(btnSafetyDemo)
                .addGap(96, 96, 96))
        );
        tabSafetyDemoLayout.setVerticalGroup(
            tabSafetyDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSafetyDemoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(tabSafetyDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabSafetyDemoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(tabSafetyDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerformID)
                            .addComponent(txtFlightID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabSafetyDemoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(tabSafetyDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSafetyDemo)
                    .addComponent(btnPerformBack))
                .addContainerGap())
        );

        tabFlightAttendant.addTab("Perform Saftey Demonstration", tabSafetyDemo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabFlightAttendant)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabFlightAttendant)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            BufferedReader br = new BufferedReader(new FileReader("flights.txt"));
            BufferedReader br1 = new BufferedReader(new FileReader("staffAssigned.txt"));

            String line;
    
            DefaultTableModel model = (DefaultTableModel) tblSchedule.getModel();
    
            while ((line = br.readLine()) != null) {
                String[] rowData = line.split(",");
                model.addRow(rowData);
            }
            
            txtAreaAttendant.setText("");

            while ((line = br1.readLine()) != null) {
                if (line.contains(attendant.getName())) {
                    txtAreaAttendant.append(line + "\n");
                }
            }
            
            br.close();
            br1.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnSafetyDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSafetyDemoActionPerformed
        String flight = txtFlightID.getText();
        File input = new File("staffAssigned.txt");
        File output = new File("temp.txt");
        
        String lineToRemove = "Staff: " + attendant.getName() + " - Department: " + attendant.getDepartment() + " - Flight: " + flight;
        
        try {
            BufferedReader reader = new BufferedReader(new FileReader(input));
            BufferedWriter writer = new BufferedWriter(new FileWriter(output));

            String line;
    
            txtAreaAttendant.setText("");

            while ((line = reader.readLine()) != null) {
                if (line.equals(lineToRemove)) {
                    continue;
                }
                writer.write(line);
                writer.newLine();
            }
            reader.close();
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        input.delete();
        output.renameTo(input);
        JOptionPane.showMessageDialog(this, "Now performing safety demonstartion for flight " + flight + ". Your schedule will be updated.");
    }//GEN-LAST:event_btnSafetyDemoActionPerformed

    private void btnPerformBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformBackActionPerformed
        staffFrame staff = new staffFrame();
        staff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerformBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendantMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendantMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendantMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendantMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlightAttendants attendant = new FlightAttendants();
                new AttendantMenu(attendant).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPerformBack;
    private javax.swing.JButton btnSafetyDemo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblPerformID;
    private javax.swing.JPanel tabAttendantFlightSchedule;
    private javax.swing.JTabbedPane tabFlightAttendant;
    private javax.swing.JPanel tabSafetyDemo;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextArea txtAreaAttendant;
    private javax.swing.JTextField txtFlightID;
    // End of variables declaration//GEN-END:variables
}
