
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kobed
 */
public class staffFrame extends javax.swing.JFrame {

    /**
     * Creates new form staffFrame
     */
    public staffFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabStaff = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCockpitName = new javax.swing.JTextField();
        txtCockpitID = new javax.swing.JTextField();
        btnCockpitLogIn = new javax.swing.JButton();
        btnCockpitBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAttendantName = new javax.swing.JTextField();
        txtAttendantID = new javax.swing.JTextField();
        btnAttendantLogIn = new javax.swing.JButton();
        btnFlightBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabStaff.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabStaffStateChanged(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Staff ID:");

        txtCockpitID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCockpitIDActionPerformed(evt);
            }
        });

        btnCockpitLogIn.setText("Log In");
        btnCockpitLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCockpitLogInActionPerformed(evt);
            }
        });

        btnCockpitBack.setText("Back");
        btnCockpitBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCockpitBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnCockpitBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnCockpitLogIn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCockpitID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCockpitName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCockpitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCockpitID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCockpitLogIn)
                    .addComponent(btnCockpitBack))
                .addContainerGap())
        );

        tabStaff.addTab("Cockpit Crew Log In", jPanel1);

        jLabel3.setText("Name:");

        jLabel4.setText("Staff ID:");

        btnAttendantLogIn.setText("Log In");
        btnAttendantLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendantLogInActionPerformed(evt);
            }
        });

        btnFlightBack.setText("Back");
        btnFlightBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAttendantName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAttendantID)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnFlightBack)
                .addGap(18, 18, 18)
                .addComponent(btnAttendantLogIn)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAttendantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAttendantID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAttendantLogIn)
                    .addComponent(btnFlightBack))
                .addContainerGap())
        );

        tabStaff.addTab("Flight Attendant Log In", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabStaff)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCockpitIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCockpitIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCockpitIDActionPerformed

    private void btnCockpitLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCockpitLogInActionPerformed
        String cockpitData = "cockpit.txt";
        System.out.println(new File(cockpitData).getAbsolutePath());
        boolean found = false;
        try (BufferedReader br = new BufferedReader(new FileReader(cockpitData))) {
            String line;
            int lineNumber = 0;

            while ((line = br.readLine()) != null) {
                lineNumber++;
                // Case-insensitive search
                if (line.toLowerCase().contains(txtCockpitName.getText().toLowerCase()) && line.contains(txtCockpitID.getText())) {
                    System.out.println("Found on line " + lineNumber + ": " + line);
                    found = true;
                    
                    String[] parts = line.split(", ");
                    String name = parts[0];
                    int age = Integer.parseInt(parts[1]);
                    int Id = Integer.parseInt(parts[2]);
                    String email = parts[3];
                    String workNum = parts[4];
                    String department = parts[5];
                    int salary = Integer.parseInt(parts[6]);
                    CockpitCrew cockpitMember = new CockpitCrew(name, age, Id, email, workNum, department, salary);
                    
                    JOptionPane.showMessageDialog(this, "Welcome Back " + txtCockpitName.getText() + "!");
                    CockpitMenu cockpit = new CockpitMenu(cockpitMember);
                    cockpit.setVisible(true);
                    this.dispose();
                }
            }

            if (!found) {
                System.out.println("Staff member not found in file.");
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCockpitLogInActionPerformed

    private void btnAttendantLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendantLogInActionPerformed
        String attendantData = "attendant.txt";
        System.out.println(new File(attendantData).getAbsolutePath());
        boolean found = false;
        try (BufferedReader br = new BufferedReader(new FileReader(attendantData))) {
            String line;
            int lineNumber = 0;

            while ((line = br.readLine()) != null) {
                lineNumber++;
                // Case-insensitive search
                if (line.toLowerCase().contains(txtAttendantName.getText().toLowerCase()) && line.contains(txtAttendantID.getText())) {
                    System.out.println("Found on line " + lineNumber + ": " + line);
                    found = true;
                    
                    String[] parts = line.split(", ");
                    String name = parts[0];
                    int age = Integer.parseInt(parts[1]);
                    int Id = Integer.parseInt(parts[2]);
                    String email = parts[3];
                    String workNum = parts[4];
                    String department = parts[5];
                    int salary = Integer.parseInt(parts[6]);
                    FlightAttendants attendantMember = new FlightAttendants(name, age, Id, email, workNum, department, salary);
                    
                    JOptionPane.showMessageDialog(this, "Welcome Back " + txtAttendantName.getText() + "!");
                    AttendantMenu attendant = new AttendantMenu(attendantMember);
                    attendant.setVisible(true);
                    this.dispose();
                }
            }

            if (!found) {
                System.out.println("Staff member not found in file.");
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAttendantLogInActionPerformed

    private void tabStaffStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabStaffStateChanged
        txtCockpitName.setText("");
        txtCockpitID.setText("");
        txtAttendantName.setText("");
        txtAttendantName.setText("");
    }//GEN-LAST:event_tabStaffStateChanged

    private void btnCockpitBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCockpitBackActionPerformed
        AmsFrame ams = new AmsFrame();
        ams.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCockpitBackActionPerformed

    private void btnFlightBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightBackActionPerformed
        AmsFrame ams = new AmsFrame();
        ams.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFlightBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendantLogIn;
    private javax.swing.JButton btnCockpitBack;
    private javax.swing.JButton btnCockpitLogIn;
    private javax.swing.JButton btnFlightBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane tabStaff;
    private javax.swing.JTextField txtAttendantID;
    private javax.swing.JTextField txtAttendantName;
    private javax.swing.JTextField txtCockpitID;
    private javax.swing.JTextField txtCockpitName;
    // End of variables declaration//GEN-END:variables
}
