//Dominic Gutierrez on 3/31/2026
import java.util.ArrayList;

/**
 * The RevenueReport class represents a report that summarizes the revenue generated by an airline.
 * It provides a method to print the report, which can include information such as total revenue,
 * revenue by flight, and revenue by ticket type.
 */
public class RevenueReport {
    ArrayList<Payment> payments = new ArrayList<>();

    public RevenueReport(ArrayList<Payment> payments) {
        this.payments = payments;
    }

    public void addPayment(Payment payment) {
        payments.add(payment);
    }

    public ArrayList<Payment> getPayments() {
        return payments;
    }

    /**
     * Prints the payment report for the airline.
     */
    public void printPaymentReport(Airline airline, ArrayList<Payment> payments) {
        System.out.println("Payment Report for " + airline.getName());
        System.out.println("------------------------------");
        for (Payment payment : payments) {
            System.out.println("Payment: $" + payment.getAmount());
        }
        System.out.println("------------------------------");
    }
}
